name: Auto-update mamba
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ssh-key: ${{ secrets.MINIFORGE_AUTOUPDATE_SSH_PRIVATE_KEY }}
      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
        with:
          miniforge-version: latest
          environment-file: .github/actions/autoupdate/environment.yml
      - run: python .github/actions/autoupdate/update.py
      - name: Create Pull Request
        id: cpr
        # This is the v3 tag but for security purposes we pin to the exact commit.
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
        with:
          commit-message: "Update mamba version"
          title: "Update mamba version"
          body: |
            This PR was created by the autoupdate action as it detected that
            the mamba version has changed and thus should be updated
            in the configuration.

            Due to limitations of Github Actions, you will need to close/reopen
            the PR to get the actions running.
          branch: autoupdate-action
          delete-branch: true
