name: Lint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
      - name: Install dependencies
        run: |
          conda install -c conda-forge shellcheck
      - name: Shellcheck
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          shellcheck --format=gcc $(find . -iname "*.sh")
          echo "::remove-matcher owner=shellcheck::"
